export const CHAOS_SEEDS = [
    // Aesthetics & Subcultures
    'Cyberpunk',
    'Vaporwave',
    'Brutalism',
    'Liminal Spaces',
    'Solarpunk',
    'Goblincore',
    'Dark Academia',
    'Cottagecore',
    'Frutiger Aero',
    'Y2K Aesthetic',
    'Steampunk',
    'Dieselpunk',
    'Cassette Futurism',
    'Glitch Art',
    'Synthwave',
    'Biopunk',
    'Atompunk',
    'Raypunk',
    'Clockpunk',
    'Decopunk',

    // Sci-Fi & Concepts
    'Megastructure',
    'Dyson Sphere',
    'Transhumanism',
    'Cybernetics',
    'Artificial Intelligence',
    'Simulation Hypothesis',
    'Quantum Computing',
    'Space Elevator',
    'Terraforming',
    'Arcology',
    'Cryptid',
    'SCP Foundation',
    'Creepypasta',
    'Urban Legend',
    'Lost Media',
    'Alternate Reality Game',
    'Analog Horror',
    'Dead Mall',
    'Abandoned Places',
    'Ghost Town',

    // Retro Tech & Niche
    'Retro-computing',
    'Mechanical Keyboard',
    'Nixie Tube',
    'Chiptune',
    'Demoscene',
    'Commodore 64',
    'Amiga',
    'Bulletin Board System',
    'Usenet',
    'Gopher (protocol)',
    'Teletext',
    'Minidisc',
    'Lofi Hip Hop',
    'Ambient Music',
    'Modular Synthesizer',

    // Nature & Science
    'Bioluminescence',
    'Deep Sea Creature',
    'Mycology',
    'Fractal',
    'Chaos Theory',
    'Tardigrade',
    'Slime Mold',
    'Ferrofluid',
    'Cymatics',
    'Synesthesia',

    // Architecture & Design
    'Metabolism (architecture)',
    'Bauhaus',
    'Memphis Group',
    'Art Deco',
    'Mid-century Modern',
    'Isometric Graphics',
    'Pixel Art',
    'Voxel',
    'Low Poly',
    ' ASCII Art'
];
